### YamlMime:ManagedReference
items:
- uid: Fantasy.ConfigTable.IConfigTable
  commentId: T:Fantasy.ConfigTable.IConfigTable
  id: IConfigTable
  parent: Fantasy.ConfigTable
  children: []
  langs:
  - csharp
  - vb
  name: IConfigTable
  nameWithType: IConfigTable
  fullName: Fantasy.ConfigTable.IConfigTable
  type: Interface
  source:
    remote:
      path: Fantasy.Net/Fantasy.Net/Runtime/Core/ConfigTable/Interface/IConfigTable.cs
      branch: main
      repo: https://github.com/qq362946/Fantasy.git
    id: IConfigTable
    path: ../Fantasy.Net/Fantasy.Net/Runtime/Core/ConfigTable/Interface/IConfigTable.cs
    startLine: 5
  assemblies:
  - Fantasy.Net
  namespace: Fantasy.ConfigTable
  summary: 表示是一个配置文件
  example: []
  syntax:
    content: public interface IConfigTable
    content.vb: Public Interface IConfigTable
  extensionMethods:
  - Fantasy.ConfigTable.IConfigTable.Fantasy.Helper.JsonHelper.ToJson``1
references:
- uid: Fantasy.ConfigTable
  commentId: N:Fantasy.ConfigTable
  href: Fantasy.html
  name: Fantasy.ConfigTable
  nameWithType: Fantasy.ConfigTable
  fullName: Fantasy.ConfigTable
  spec.csharp:
  - uid: Fantasy
    name: Fantasy
    href: Fantasy.html
  - name: .
  - uid: Fantasy.ConfigTable
    name: ConfigTable
    href: Fantasy.ConfigTable.html
  spec.vb:
  - uid: Fantasy
    name: Fantasy
    href: Fantasy.html
  - name: .
  - uid: Fantasy.ConfigTable
    name: ConfigTable
    href: Fantasy.ConfigTable.html
- uid: Fantasy.ConfigTable.IConfigTable.Fantasy.Helper.JsonHelper.ToJson``1
  commentId: M:Fantasy.Helper.JsonHelper.ToJson``1(``0)
  parent: Fantasy.Helper.JsonHelper
  definition: Fantasy.Helper.JsonHelper.ToJson``1(``0)
  href: Fantasy.Helper.JsonHelper.html#Fantasy_Helper_JsonHelper_ToJson__1___0_
  name: ToJson<IConfigTable>(IConfigTable)
  nameWithType: JsonHelper.ToJson<IConfigTable>(IConfigTable)
  fullName: Fantasy.Helper.JsonHelper.ToJson<Fantasy.ConfigTable.IConfigTable>(Fantasy.ConfigTable.IConfigTable)
  nameWithType.vb: JsonHelper.ToJson(Of IConfigTable)(IConfigTable)
  fullName.vb: Fantasy.Helper.JsonHelper.ToJson(Of Fantasy.ConfigTable.IConfigTable)(Fantasy.ConfigTable.IConfigTable)
  name.vb: ToJson(Of IConfigTable)(IConfigTable)
  spec.csharp:
  - uid: Fantasy.Helper.JsonHelper.ToJson``1(Fantasy.ConfigTable.IConfigTable)
    name: ToJson
    href: Fantasy.Helper.JsonHelper.html#Fantasy_Helper_JsonHelper_ToJson__1___0_
  - name: <
  - uid: Fantasy.ConfigTable.IConfigTable
    name: IConfigTable
    href: Fantasy.ConfigTable.IConfigTable.html
  - name: '>'
  - name: (
  - uid: Fantasy.ConfigTable.IConfigTable
    name: IConfigTable
    href: Fantasy.ConfigTable.IConfigTable.html
  - name: )
  spec.vb:
  - uid: Fantasy.Helper.JsonHelper.ToJson``1(Fantasy.ConfigTable.IConfigTable)
    name: ToJson
    href: Fantasy.Helper.JsonHelper.html#Fantasy_Helper_JsonHelper_ToJson__1___0_
  - name: (
  - name: Of
  - name: " "
  - uid: Fantasy.ConfigTable.IConfigTable
    name: IConfigTable
    href: Fantasy.ConfigTable.IConfigTable.html
  - name: )
  - name: (
  - uid: Fantasy.ConfigTable.IConfigTable
    name: IConfigTable
    href: Fantasy.ConfigTable.IConfigTable.html
  - name: )
- uid: Fantasy.Helper.JsonHelper.ToJson``1(``0)
  commentId: M:Fantasy.Helper.JsonHelper.ToJson``1(``0)
  href: Fantasy.Helper.JsonHelper.html#Fantasy_Helper_JsonHelper_ToJson__1___0_
  name: ToJson<T>(T)
  nameWithType: JsonHelper.ToJson<T>(T)
  fullName: Fantasy.Helper.JsonHelper.ToJson<T>(T)
  nameWithType.vb: JsonHelper.ToJson(Of T)(T)
  fullName.vb: Fantasy.Helper.JsonHelper.ToJson(Of T)(T)
  name.vb: ToJson(Of T)(T)
  spec.csharp:
  - uid: Fantasy.Helper.JsonHelper.ToJson``1(``0)
    name: ToJson
    href: Fantasy.Helper.JsonHelper.html#Fantasy_Helper_JsonHelper_ToJson__1___0_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: Fantasy.Helper.JsonHelper.ToJson``1(``0)
    name: ToJson
    href: Fantasy.Helper.JsonHelper.html#Fantasy_Helper_JsonHelper_ToJson__1___0_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: Fantasy.Helper.JsonHelper
  commentId: T:Fantasy.Helper.JsonHelper
  parent: Fantasy.Helper
  href: Fantasy.Helper.JsonHelper.html
  name: JsonHelper
  nameWithType: JsonHelper
  fullName: Fantasy.Helper.JsonHelper
- uid: Fantasy.Helper
  commentId: N:Fantasy.Helper
  href: Fantasy.html
  name: Fantasy.Helper
  nameWithType: Fantasy.Helper
  fullName: Fantasy.Helper
  spec.csharp:
  - uid: Fantasy
    name: Fantasy
    href: Fantasy.html
  - name: .
  - uid: Fantasy.Helper
    name: Helper
    href: Fantasy.Helper.html
  spec.vb:
  - uid: Fantasy
    name: Fantasy
    href: Fantasy.html
  - name: .
  - uid: Fantasy.Helper
    name: Helper
    href: Fantasy.Helper.html
